name: code check

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Проверяю код линтером..."
      - run: sleep 2
      - run: exit 1
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - run: echo "Запускаю тесты..."
      - run: sleep 3
      - run: echo "Тесты пройдены!"
