name: Condition с секретом

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    if:  secrets.MY_TOKEN != '' 
    steps:
      - run: echo "секрет есть"
  deploy:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - run: echo "деплой..."
