name: Matrix из двух параметров
on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [16, 18]
        
    steps:
      - uses: actions/checkout@v4
      
      - name: устанавливаем Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: выводим версию
        run: node -v
      
      - name: выводим ОС
        run: echo "Запущено на ${{ matrix.os }}"
