name: Secrets Demo
on: 
  push:

jobs:
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Длина токена: ${#MY_TOKEN} символов"
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
