name: Последовательный пайплайн

on:
  push:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - run: echo "установка зависимостей"
  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - run: echo "запуск тестов..."
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "деплой на сервер..."
